kooper/api/urls.py
from django.urls import path
from rest_framework.generics import RetrieveAPIView

from bingo.models import BingoModel

from .serializers import BingoSerializer

urlpatterns = [
    path('<int:user_id>/',
         RetrieveAPIView.as_view(queryset=BingoModel.objects.all(),
                                 serializer_class=BingoSerializer,
                                 lookup_field='user_id'))
]

kooper/bingo/urls.py
from django.urls import path

from . import views

app_name = 'bingo'

urlpatterns = [
     path('', views.main, name='main'),
     path('big/', views.CreateMatrixView.as_view(), name='create'),
     path('small/', views.CreateMatrixViewThree.as_view(), name='create2'),
     path('matrix/', views.push_view, name='index'),
     path('matrix2/', views.push_view2, name='index2'),
     path('calculateprogressonlyservicefunction/', views.calc_progress,
          name='calc'),
     path('calculateprogressonlyservicefunction2/', views.calc_progress2,
          name='calc2'),
]

kooper/kooper/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView

urlpatterns = [
    path('', include('bingo.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('bingo:main'),
        ),
        name='registration',
    ),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
]

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.handler500'

kooper/templates/includes/header.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<!-- Ваш код кнопок -->
<nav class="navbar navbar-light" style="background-color: #1973A0;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'bingo:main' %}"><img src="{% static 'img/logo.png' %}" width="60" height="70" alt=""></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Движениe по сайту
          </a>
          <ul id="menu"  class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            {% if user.is_authenticated %}

            <li><a class="dropdown-item" href="{% url 'bingo:create' %}">Создать/Обновить бинго</a></li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Выйти</a></li>
            <li><a class="dropdown-item" href="{% url 'bingo:index' %}">Мое бинго</a></li>
            {% else %}
            
            <li><a class="dropdown-item" href="{% url 'login' %}">Войти</a></li>
            <li><a class="dropdown-item" href="{% url 'registration' %}">Регистрация</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>