kooper/api/urls.py
from django.urls import path
from rest_framework.generics import RetrieveAPIView

from bingo.models import BingoModel

from .serializers import BingoSerializer

urlpatterns = [
    path('<int:user_id>/',
         RetrieveAPIView.as_view(queryset=BingoModel.objects.all(),
                                 serializer_class=BingoSerializer,
                                 lookup_field='user_id'))
]

kooper/bingo/urls.py
from django.urls import path

from . import views

app_name = 'bingo'

urlpatterns = [
     path('', views.main, name='main'),
     path('big/', views.CreateMatrixView.as_view(), name='create'),
     path('small/', views.CreateMatrixViewThree.as_view(), name='create2'),
     path('matrix/', views.push_view, name='index'),
     path('matrix2/', views.push_view2, name='index2'),
     path('calculateprogressonlyservicefunction/', views.calc_progress,
          name='calc'),
     path('calculateprogressonlyservicefunction2/', views.calc_progress2,
          name='calc2'),
]

kooper/kooper/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView

urlpatterns = [
    path('', include('bingo.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('bingo:main'),
        ),
        name='registration',
    ),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
]

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.handler500'

kooper/bingo/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class DataModel(models.Model):
    for i in range(1, 26):
        locals()[f'field{i}'] = models.CharField(max_length=20)
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                verbose_name='пользователь',
                                unique=True)
    bingo = models.OneToOneField('BingoModel', on_delete=models.CASCADE,
                                 unique=True)

    def __str__(self):
        return f"DataModel ({self.pk})"


class BingoModel(models.Model):
    for i in range(1, 26):
        locals()[f'field{i}'] = models.BooleanField(default=False)
    old_progress = models.IntegerField(default=0)
    progress = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                unique=True)


class DataModelThree(models.Model):
    for i in range(1, 10):
        locals()[f'field{i}'] = models.CharField(max_length=20)
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                verbose_name='пользователь',
                                unique=True)
    bingo = models.OneToOneField('BingoModelThree', on_delete=models.CASCADE,
                                 unique=True)

    def __str__(self):
        return f"BingoModelThree ({self.pk})"


class BingoModelThree(models.Model):
    for i in range(1, 10):
        locals()[f'field{i}'] = models.BooleanField(default=False)
    old_progress = models.IntegerField(default=0)
    progress = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                unique=True)


class MainMod(models.Model):
    """False 3x3  True 5x5"""
    mod = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                unique=True, related_name='mod')

kooper/bingo/forms.py
from django import forms

from .models import DataModel, DataModelThree, MainMod


class DataForm(forms.ModelForm):
    class Meta:
        model = DataModel
        exclude = ('user', 'bingo')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.convert_fields_to_textarea()

    def convert_fields_to_textarea(self):
        for field_name in self.fields.keys():
            self.fields[field_name].widget = forms.Textarea(
                attrs={'maxlength': '18', 'id': 'fieldforinfo'}
                )


class DataFormThree(forms.ModelForm):
    class Meta:
        model = DataModelThree
        exclude = ('user', 'bingo')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.convert_fields_to_textarea()

    def convert_fields_to_textarea(self):
        for field_name in self.fields.keys():
            self.fields[field_name].widget = forms.Textarea(
                attrs={'maxlength': '18', 'id': 'fieldforinfo'}
                )


class TestForm(forms.ModelForm):
    GRID_CHOICES = (
        (False, '3x3'),
        (True, '5x5'),
    )
    mod = forms.ChoiceField(choices=GRID_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = MainMod
        fields = ('mod',)

kooper/bingo/views.py
import json
from typing import Any, Dict
from django import http

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.models import BaseModelForm
from django.http import HttpResponse, JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import DataForm, DataFormThree, TestForm
from .models import BingoModel, DataModel, DataModelThree, BingoModelThree, MainMod
from .utils import calc


class CreateMatrixView(LoginRequiredMixin, CreateView):
    model = DataModel
    form_class = DataForm
    template_name = 'bingo/form.html'
    success_url = reverse_lazy('bingo:index')

    def dispatch(self, request, *args: Any, **kwargs: Any) -> HttpResponse:
        try:
            if MainMod.objects.get(user=request.user).mod:
                return super().dispatch(request, *args, **kwargs)
            return redirect('bingo:create2')
        except MainMod.DoesNotExist:
            return redirect('bingo:main')

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        bingo, _ = BingoModel.objects.get_or_create(user=user)
        form.instance.bingo = bingo
        new = form.cleaned_data
        try:
            old = DataModel.objects.get(user=user)
        except DataModel.DoesNotExist:
            old = False

        if old:
            for i in range(1, 26):
                field = f'field{i}'
                if getattr(old, field) != new[field]:
                    setattr(bingo, field, False)
            bingo.save()
        DataModel.objects.update_or_create(
                user=user,
                defaults=form.cleaned_data,
                bingo=bingo
        )
        return redirect(self.success_url)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = self.request.user
        try:
            data = DataModel.objects.get(user=user)
        except DataModel.DoesNotExist:
            data = False
        if data:
            initial = {}
            for i in range(1, 26):
                field = f'field{i}'
                obj = getattr(data, field)
                initial[field] = obj
            kwargs['initial'] = initial
        return kwargs



@login_required
def push_view(request):
    try:
        if not MainMod.objects.get(user=request.user).mod:
            return redirect('bingo:index2')
    except MainMod.DoesNotExist:
        return redirect('bingo:main')
    try:
        bingo = BingoModel.objects.get(user=request.user)
    except BingoModel.DoesNotExist:
        return redirect('bingo:create')
    if request.method == 'POST':
        data = json.loads(request.body)
        number = data['number']
        field = f'field{number}'
        val = getattr(bingo, field)
        if val:
            setattr(bingo, field, False)
        else:
            setattr(bingo, field, True)
        bingo.save()
    template = 'bingo/list.html'
    data = DataModel.objects.get(user=request.user)
    context = {'list': data, 'bingo': bingo}
    return render(request, template, context)


def calc_progress(request):
    bingo, flag = calc(BingoModel.objects.get(user=request.user), 5)
    bingo.save()
    return JsonResponse({'data': bingo.progress, 'flag': flag})


class CreateMatrixViewThree(LoginRequiredMixin, CreateView):
    model = DataModelThree
    form_class = DataFormThree
    template_name = 'bingo/form.html'
    success_url = reverse_lazy('bingo:index2')

    def dispatch(self, request, *args: Any, **kwargs: Any) -> HttpResponse:
        try:
            if not MainMod.objects.get(user=request.user).mod:
                return super().dispatch(request, *args, **kwargs)
            return redirect('bingo:create')
        except MainMod.DoesNotExist:
            return redirect('bingo:main')

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        bingo, _ = BingoModelThree.objects.get_or_create(user=user)
        form.instance.bingo = bingo
        new = form.cleaned_data
        try:
            old = DataModelThree.objects.get(user=user)
        except DataModelThree.DoesNotExist:
            old = False

        if old:
            for i in range(1, 10):
                field = f'field{i}'
                if getattr(old, field) != new[field]:
                    setattr(bingo, field, False)
            bingo.save()
        DataModelThree.objects.update_or_create(
                user=user,
                defaults=form.cleaned_data,
                bingo=bingo
        )
        return redirect(self.success_url)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = self.request.user
        try:
            data = DataModelThree.objects.get(user=user)
        except DataModelThree.DoesNotExist:
            data = False
        if data:
            initial = {}
            for i in range(1, 10):
                field = f'field{i}'
                obj = getattr(data, field)
                initial[field] = obj
            kwargs['initial'] = initial
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mod'] = 3
        return context


@login_required
def push_view2(request):
    try:
        if MainMod.objects.get(user=request.user).mod:
            return redirect('bingo:index')
    except MainMod.DoesNotExist:
        return redirect('bingo:main')
    try:
        bingo = BingoModelThree.objects.get(user=request.user)
    except BingoModelThree.DoesNotExist:
        return redirect('bingo:create2')
    if request.method == 'POST':
        data = json.loads(request.body)
        number = data['number']
        field = f'field{number}'
        val = getattr(bingo, field)
        if val:
            setattr(bingo, field, False)
        else:
            setattr(bingo, field, True)
        bingo.save()
    template = 'bingo/list2.html'
    data = DataModelThree.objects.get(user=request.user)
    context = {'list': data, 'bingo': bingo}
    return render(request, template, context)


def calc_progress2(request):
    bingo, flag = calc(BingoModelThree.objects.get(user=request.user), 3)
    bingo.save()
    return JsonResponse({'data': bingo.progress, 'flag': flag})


@login_required
def main(request):
    user = request.user
    mod_instance, created = MainMod.objects.update_or_create(user=user)

    if request.method == 'POST':
        form = TestForm(request.POST, instance=mod_instance)
        if form.is_valid():
            form.save()
            return redirect('bingo:index')
    else:
        form = TestForm(instance=mod_instance)

    return render(request, 'bingo/main.html', {'form': form})

kooper/templates/bingo/list.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block content %}
<div id="matrix">
  <div class="animation">
    <h3 class="cssanimation sequence rotateXIn"></h3>
  
  </div>
  <div id="row">
    <div id="square" class="field1" onclick="sendData(1)">
      {% if bingo.field1 %}
        <i id="check1" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field1 }}
    </div>
    <div id="square" class="field2" onclick="sendData(2)">
      {% if bingo.field2 %}
        <i id="check2" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field2 }}
    </div>
    <div id="square" class="field3" onclick="sendData(3)">
      {% if bingo.field3 %}
        <i id="check3" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field3 }}
    </div>
    <div id="square" class="field4" onclick="sendData(4)">
      {% if bingo.field4 %}
        <i id="check4" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field4 }}
    </div>
    <div id="square" class="field5" onclick="sendData(5)">
      {% if bingo.field5 %}
        <i id="check5" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field5 }}
    </div>
  </div>
  <div id="row">
    <div id="square" class="field6" onclick="sendData(6)">
      {% if bingo.field6 %}
        <i id="check6" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field6 }}
    </div>
    <div id="square" class="field7" onclick="sendData(7)">
      {% if bingo.field7 %}
        <i id="check7" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field7 }}
    </div>
    <div id="square" class="field8" onclick="sendData(8)">
      {% if bingo.field8 %}
        <i id="check8" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field8 }}
    </div>
    <div id="square" class="field9" onclick="sendData(9)">
      {% if bingo.field9 %}
        <i id="check9" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field9 }}
    </div>
    <div id="square" class="field10" onclick="sendData(10)">
      {% if bingo.field10 %}
        <i id="check10" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field10 }}
    </div>
  </div>
  <div id="row">
    <div id="square" class="field11" onclick="sendData(11)">
      {% if bingo.field11 %}
        <i id="check11" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field11 }}
    </div>
    <div id="square" class="field12" onclick="sendData(12)">
      {% if bingo.field12 %}
        <i id="check12" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field12 }}
    </div>
    <div id="square" class="field13" onclick="sendData(13)">
      {% if bingo.field13 %}
        <i id="check13" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field13 }}
    </div>
    <div id="square" class="field14" onclick="sendData(14)">
      {% if bingo.field14 %}
        <i id="check14" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field14 }}
    </div>
    <div id="square" class="field15" onclick="sendData(15)">
      {% if bingo.field15 %}
        <i id="check15" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field15 }}
    </div>
  </div>
  <div id="row">
    <div id="square" class="field16" onclick="sendData(16)">
      {% if bingo.field16 %}
        <i id="check16" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field16 }}
    </div>
    <div id="square" class="field17" onclick="sendData(17)">
      {% if bingo.field17 %}
        <i id="check17" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field17 }}
    </div>
    <div id="square" class="field18" onclick="sendData(18)">
      {% if bingo.field18 %}
        <i id="check18" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field18 }}
    </div>
    <div id="square" class="field19" onclick="sendData(19)">
      {% if bingo.field19 %}
        <i id="check19" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field19 }}
    </div>
    <div id="square" class="field20" onclick="sendData(20)">
      {% if bingo.field20 %}
        <i id="check20" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field20 }}
    </div>
  </div>
  <div id="row">
    <div id="square" class="field21" onclick="sendData(21)">
      {% if bingo.field21 %}
        <i id="check21" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field21 }}
    </div>
    <div id="square" class="field22" onclick="sendData(22)">
      {% if bingo.field22 %}
        <i id="check22" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field22 }}
    </div>
    <div id="square" class="field23" onclick="sendData(23)">
      {% if bingo.field23 %}
        <i id="check23" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field23 }}
    </div>
    <div id="square" class="field24" onclick="sendData(24)">
      {% if bingo.field24 %}
        <i id="check24" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field24 }}
    </div>
    <div id="square" class="field25" onclick="sendData(25)">
      {% if bingo.field25 %}
        <i id="check25" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field25 }}
    </div>
  </div>
  {% csrf_token %}
</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

function sendData(number) {
  // Получаем значение CSRF-токена из cookie
  const csrfToken = getCookie('csrftoken');

  // Создаем объект с данными для отправки в JSON формате
  const data = {
    number: number
  };

  // Отправляем POST-запрос с использованием библиотеки axios
  axios.post('{% url "bingo:index" %}', data, {
    headers: {
      'X-CSRFToken': csrfToken
    }
  })
    .then(response => {
      console.log('Запрос успешно отправлен');
      CheckProgress()
    })
    .catch(error => {
      console.error('Произошла ошибка при отправке запроса:', error.message);
    });
    toggleTag(number)

}

// Функция для получения значения cookie по имени
function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}

// посылает get запрос для проверки прогресса

function CheckProgress() {
  var xhr = new XMLHttpRequest();

  xhr.onload = function() {
    if (xhr.status === 200) {
      // Получаем значение из ответа
      var response = JSON.parse(xhr.responseText);
      var data = response.data;
      console.log(response.flag)
      // Проверяем значение флага
      if (response.flag === true) {
        // Создаем новый элемент
        var newAnimationDiv = document.createElement("div");
        newAnimationDiv.classList.add("animation");

        var h3Element = document.createElement("h3");
        h3Element.classList.add("cssanimation", "sequence", "rotateXIn");
        h3Element.innerText = "BINGO  ";

        newAnimationDiv.appendChild(h3Element);

        // Вставляем новый элемент после элемента с классом "animation"
        var currentAnimationDiv = document.querySelector(".animation");
        currentAnimationDiv.insertAdjacentElement("afterend", newAnimationDiv);

        // Удаляем новый элемент через 2 секунды
        setTimeout(function() {
          newAnimationDiv.remove();
        }, 2000);
      }

      // Вставляем значение на страницу
      // document.getElementById("result").innerHTML = data + " из 8";
    } else {
      console.log('Ошибка запроса. Статус: ' + xhr.status);
    }
  };

  xhr.open('GET', '{% url "bingo:calc" %}', true);

  xhr.send();
}

function toggleTag(num) {
  var tagContainer = document.querySelector('.field' + num);
  
  // Проверяем, есть ли уже тег в контейнере
  if (tagContainer.contains(document.getElementById("check" + num))) {
    // Если тег уже есть, удаляем его
    var tag = document.getElementById("check" + num);
    tagContainer.removeChild(tag);
  } else {
    // Если тега нет, создаем и добавляем его
    var tag = document.createElement("i");
    tag.id = "check" + num;
    tag.className = "bi bi-check-square-fill";
    tagContainer.appendChild(tag);
  }
}
</script>
{% endblock %}

kooper/templates/bingo/list2.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block content %}
<div id="matrix" >
  <div class="animation">
    <!-- <h3 class="cssanimation sequence rotateXIn">BINGO</h3> -->
  
  </div>
  <!-- <div id="result">{{ bingo.progress }} из 8</div> -->
  <div id="row">
    <div id="square" class="field1" onclick="sendData(1)">
      {% if bingo.field1 %}
        <i id="check1" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field1 }}
    </div>
    <div id="square" class="field2" onclick="sendData(2)">
      {% if bingo.field2 %}
        <i id="check2" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field2 }}
    </div>
    <div id="square" class="field3" onclick="sendData(3)">
      {% if bingo.field3 %}
        <i id="check3" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field3 }}
    </div>
    </div>
  </div>
  <div id="row">
    <div id="square" class="field4" onclick="sendData(4)">
      {% if bingo.field4 %}
        <i id="check4" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field4 }}
    </div>
    <div id="square" class="field5" onclick="sendData(5)">
      {% if bingo.field5 %}
        <i id="check5" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field5 }}
    </div>
    <div id="square" class="field6" onclick="sendData(6)">
      {% if bingo.field6 %}
        <i id="check6" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field6 }}
    </div>
  </div>
  <div id="row">
    <div id="square" class="field7" onclick="sendData(7)">
      {% if bingo.field7 %}
        <i id="check7" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field7 }}
    </div>
    <div id="square" class="field8" onclick="sendData(8)">
      {% if bingo.field8 %}
        <i id="check8" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field8 }}
    </div>
    <div id="square" class="field9" onclick="sendData(9)">
      {% if bingo.field9 %}
        <i id="check9" class="bi bi-check-square-fill"></i>
      {% endif %}
      {{ list.field9 }}
    </div>
  </div>
  {% csrf_token %}
</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

function sendData(number) {
  // Получаем значение CSRF-токена из cookie
  const csrfToken = getCookie('csrftoken');

  // Создаем объект с данными для отправки в JSON формате
  const data = {
    number: number
  };

  // Отправляем POST-запрос с использованием библиотеки axios
  axios.post('{% url "bingo:index2" %}', data, {
    headers: {
      'X-CSRFToken': csrfToken
    }
  })
    .then(response => {
      console.log('Запрос успешно отправлен');
      CheckProgress()
    })
    .catch(error => {
      console.error('Произошла ошибка при отправке запроса:', error.message);
    });
    toggleTag(number)

}

// Функция для получения значения cookie по имени
function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}

// посылает get запрос для проверки прогресса

function CheckProgress() {
  var xhr = new XMLHttpRequest();

  xhr.onload = function() {
    if (xhr.status === 200) {
      // Получаем значение из ответа
      var response = JSON.parse(xhr.responseText);
      var data = response.data;

      // Проверяем значение флага
      if (response.flag === true) {
        // Создаем новый элемент
        var newAnimationDiv = document.createElement("div");
        newAnimationDiv.classList.add("animation");

        var h3Element = document.createElement("h3");
        h3Element.classList.add("cssanimation", "sequence", "rotateXIn");
        h3Element.innerText = "BINGO";

        newAnimationDiv.appendChild(h3Element);

        // Вставляем новый элемент после элемента с классом "animation"
        var currentAnimationDiv = document.querySelector(".animation");
        currentAnimationDiv.insertAdjacentElement("afterend", newAnimationDiv);

        // Удаляем новый элемент через 2 секунды
        setTimeout(function() {
          newAnimationDiv.remove();
        }, 2000);
      }

      // Вставляем значение на страницу
      // document.getElementById("result").innerHTML = data + " из 8";
    } else {
      console.log('Ошибка запроса. Статус: ' + xhr.status);
    }
  };

  xhr.open('GET', '{% url "bingo:calc2" %}', true);

  xhr.send();
}

function toggleTag(num) {
  var tagContainer = document.querySelector('.field' + num);
  
  // Проверяем, есть ли уже тег в контейнере
  if (tagContainer.contains(document.getElementById("check" + num))) {
    // Если тег уже есть, удаляем его
    var tag = document.getElementById("check" + num);
    tagContainer.removeChild(tag);
  } else {
    // Если тега нет, создаем и добавляем его
    var tag = document.createElement("i");
    tag.id = "check" + num;
    tag.className = "bi bi-check-square-fill";
    tagContainer.appendChild(tag);
  }
}
</script>
{% endblock %}

kooper/templates/bingo/qwe.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block content %}
<div id="matrix">
  <h2><div id="result">{{ bingo.progress }} из 12</div></h2>
  {% for field in fields %}
    <div id="row">
      <div id="square" class="field{{ forloop.counter }}" onclick="sendData({{ forloop.counter }})">
        {% if bingo|getattr:field %}
          <i id="check{{ forloop.counter }}" class="bi bi-check-square-fill"></i>
        {% endif %}
        {{ list|getattr:field }}
      </div>
    </div>
  {% endfor %}
</div>
  {% csrf_token %}
</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

function sendData(number) {
  // Получаем значение CSRF-токена из cookie
  const csrfToken = getCookie('csrftoken');

  // Создаем объект с данными для отправки в JSON формате
  const data = {
    number: number
  };

  // Отправляем POST-запрос с использованием библиотеки axios
  axios.post('{% url "bingo:index" %}', data, {
    headers: {
      'X-CSRFToken': csrfToken
    }
  })
    .then(response => {
      console.log('Запрос успешно отправлен');
      CheckProgress()
    })
    .catch(error => {
      console.error('Произошла ошибка при отправке запроса:', error.message);
    });
    toggleTag(number)

}

// Функция для получения значения cookie по имени
function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}

// посылает get запрос для проверки прогресса

function CheckProgress() {
  var xhr = new XMLHttpRequest();

  xhr.onload = function() {
    if (xhr.status === 200) {
      // Получаем значение из ответа

      var response = JSON.parse(xhr.responseText);
      var data = response.data;

      // Вставляем значение на страницу
      document.getElementById("result").innerHTML = data + "    из 12";
    } else {
      console.log('Ошибка запроса. Статус: ' + xhr.status);
    }
  };

  xhr.open('GET', '{% url "bingo:calc" %}', true);

  xhr.send();
}

function toggleTag(num) {
  var tagContainer = document.querySelector('.field' + num);
  
  // Проверяем, есть ли уже тег в контейнере
  if (tagContainer.contains(document.getElementById("check" + num))) {
    // Если тег уже есть, удаляем его
    var tag = document.getElementById("check" + num);
    tagContainer.removeChild(tag);
  } else {
    // Если тега нет, создаем и добавляем его
    var tag = document.createElement("i");
    tag.id = "check" + num;
    tag.className = "bi bi-check-square-fill";
    tagContainer.appendChild(tag);
  }
}
</script>
{% endblock %}